### ISSUE TITLE
lemmy

### ISSUE THREAD

**Issue by RustoMCSpit** [offa/android-foss#297] opened 2023-08-06 19:59 UTC
https://github.com/thunder-app/thunder
https://github.com/bqv/slide

**Comment by shuvashish76** [comment] 2023-08-07 04:39
Duplicate of #290

**Comment by offa** [comment] 2023-08-07 17:44
@RustoMCSpit I have moved your suggestions to #290. I don't know a way to merge issues, so let's continue the discussion in #290.

**Closed by offa** 2023-08-07 17:44 UTC
Labels: app-proposal
